### ISSUE TITLE
cmake build failure liblwgeom.h

### ISSUE THREAD

**Issue by chris-english** [Oslandia/horao#23]
chris@jacie:~/Downloads/horao/build$ cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Setting build type to 'Debug' as none was specified.
-- Found osgQt: /usr/lib/libosgQt.so  
-- Found osgViewer: /usr/lib/libosgViewer.so  
-- Found osgGA: /usr/lib/libosgGA.so  
-- Found osgDB: /usr/lib/libosgDB.so  
-- Found osgUtil: /usr/lib/libosgUtil.so  
-- Found osgText: /usr/lib/libosgText.so  
-- Found osgTerrain: /usr/lib/libosgTerrain.so  
-- Found osg: /usr/lib/libosg.so  
-- Found OpenThreads: /usr/lib/libOpenThreads.so  
-- Found OpenSceneGraph: /usr/lib/libosgQt.so;/usr/lib/libosgViewer.so;/usr/lib/libosgGA.so;/usr/lib/libosgDB.so;/usr/lib/libosgUtil.so;/usr/lib/libosgText.so;/usr/lib/libosgTerrain.so;/usr/lib/libosg.so;/usr/lib/libOpenThreads.so (found version "3.2.1") 
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libGL.so  
-- Found GDAL: /usr/local/lib/libgdal.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/chris/Downloads/horao/build
chris@jacie:~/Downloads/horao/build$ make
Scanning dependencies of target horao
[  6%] Building CXX object src/viewer/CMakeFiles/horao.dir/ViewerWidget.cpp.o
[ 13%] Building CXX object src/viewer/CMakeFiles/horao.dir/Interpreter.cpp.o
Linking CXX shared library ../../lib/libhorao.so
[ 13%] Built target horao
Scanning dependencies of target Interpreter_test
[ 20%] Building CXX object src/viewer/CMakeFiles/Interpreter_test.dir/Interpreter_test.cpp.o
Linking CXX executable ../../bin/Interpreter_test
[ 20%] Built target Interpreter_test
Scanning dependencies of target horaoViewer
[ 26%] Building CXX object src/viewer/CMakeFiles/horaoViewer.dir/main.cpp.o
Linking CXX executable ../../bin/horaoViewer
[ 26%] Built target horaoViewer
Scanning dependencies of target poly2tri
[ 33%] Building CXX object src/poly2tri/CMakeFiles/poly2tri.dir/sweep/advancing_front.cc.o
[ 40%] Building CXX object src/poly2tri/CMakeFiles/poly2tri.dir/sweep/cdt.cc.o
[ 46%] Building CXX object src/poly2tri/CMakeFiles/poly2tri.dir/sweep/sweep.cc.o
[ 53%] Building CXX object src/poly2tri/CMakeFiles/poly2tri.dir/sweep/sweep_context.cc.o
[ 60%] Building CXX object src/poly2tri/CMakeFiles/poly2tri.dir/common/shapes.cc.o
Linking CXX shared library ../../lib/libpoly2tri.so
[ 60%] Built target poly2tri
Scanning dependencies of target SFosg_test
[ 66%] Building CXX object src/osgGIS/CMakeFiles/SFosg_test.dir/SFosg_test.cpp.o
[ 73%] Building CXX object src/osgGIS/CMakeFiles/SFosg_test.dir/SFosg.cpp.o
In file included from /home/chris/Downloads/horao/src/osgGIS/SFosg.cpp:24:0:
/usr/local/include/liblwgeom.h:1917:56: error: new declaration ‘char* strcasestr(const char*, const char*)’
 extern char *strcasestr(const char *s, const char *find);
                                                        ^
In file included from /usr/local/include/osg/Uniform:33:0,
                 from /usr/local/include/osg/StateSet:20,
                 from /usr/local/include/osg/State:18,
                 from /usr/local/include/osg/RenderInfo:17,
                 from /usr/local/include/osg/Drawable:21,
                 from /usr/local/include/osg/Geometry:17,
                 from /home/chris/Downloads/horao/src/osgGIS/SFosg.h:26,
                 from /home/chris/Downloads/horao/src/osgGIS/SFosg.cpp:19:
/usr/include/string.h:369:26: error: ambiguates old declaration ‘const char* strcasestr(const char*, const char*)’
 extern "C++" const char *strcasestr (const char *__haystack,
                          ^
make[2]: *** [src/osgGIS/CMakeFiles/SFosg_test.dir/SFosg.cpp.o] Error 1
make[1]: *** [src/osgGIS/CMakeFiles/SFosg_test.dir/all] Error 2
make: *** [all] Error 2
chris@jacie:~/Downloads/horao/build$ 

This is as far as I get.  Looking for the right needle in the __haystack,

Any help appreciated.
Thanks,
Chris

**Comment by chris-english** [comment]
Sorry, Ubuntu 14.04 build environment

**Comment by vmora** [comment]
if you look into /usr/local/include/liblwgeom.h, strcasestr declaration should be enclosed in an `#ifdef HAVE_STRCASESTR`.

Can you try adding that definition an see if it fixes the problem ?

**Comment by chris-english** [comment]
This is what is in liblwgeom.h at line 1917:
#ifndef HAVE_STRCASESTR
extern char *strcasestr(const char *s, const char *find);
#endif

**Comment by chris-english** [comment]
Do you mean change the #ifndef to #ifdef?

**Comment by vmora** [comment]
no, just add

```
#define HAVE_STRCASESTR
```
before line 19 in /home/chris/Downloads/horao/src/osgGIS/SFosg.h

**Comment by chris-english** [comment]
That change fixed STRCASESTR.
Now:
[ 73%] Built target SFosg_test
Scanning dependencies of target osgdb_mnt
[ 80%] Building CXX object src/osgGIS/CMakeFiles/osgdb_mnt.dir/ReaderWriterMNT.cpp.o
/home/chris/Downloads/horao/src/osgGIS/ReaderWriterMNT.cpp:35:28: fatal error: gdal/gdal_priv.h: No such file or directory
 #include <gdal/gdal_priv.h>
                            ^
compilation terminated.
make[2]: *** [src/osgGIS/CMakeFiles/osgdb_mnt.dir/ReaderWriterMNT.cpp.o] Error 1
make[1]: *** [src/osgGIS/CMakeFiles/osgdb_mnt.dir/all] Error 2
make: *** [all] Error 2

which is in:

chris@jacie:~/Downloads/horao/build$ sudo locate gdal_priv.h
/home/chris/Downloads/gdal/gdal/gcore/gdal_priv.h
/usr/local/include/gdal_priv.h

**Comment by chris-english** [comment]
did I miss setting gdal include separately in cmake build?

**Comment by vmora** [comment]
I think I've had this problem before, this is du to a different place for the "make install"-ed gdal and the systems one, you can simply change the include in ReaderWriterMNT.cpp

**Comment by chris-english** [comment]
Here"s what I've tried:
#include /the/full/path/gdal_priv.h between the carrots<> (so I don't know markdown as well)
which merely demonstrates how little c++ i know
then tried putting FindGDAL.cmake (from QGIS github) in /horao/cmake with it's other Find*.cmake friends, which didn't work.
So what would the simply changet to ReaderWriter look like?

**Comment by vmora** [comment]
Replace 

```c++
#include <gdal/gdal_priv.h>
```

by 

```c++
#include <gdal_priv.h>
```

and it should be ok.

**Comment by chris-english** [comment]
OK - so, learned a very little bit of c++
#include /</usr/local/include/gdal_priv.h> for ReadWriterMNT.cpp and ReadWriterPOSTGIS.cpp
#include /</usr/local/include/cpgl_conv.h> again for both(the leading front slash /< is just for escaping this comment display and wasn't used of course.)
And you get:
[100%] Generating resources_rc.py
[100%] Built target qgis_plugin

Very exciting, now on the rest...

**Comment by chris-english** [comment]
#includes for both ReadWriterMNT.cpp and ReadWriterPOSTGIS.cpp need to be changed for the files gdal_priv.h and quite possibly cpl_conv.h
This might come up if you've built say GDAL 2.0.0 from source and its installed in /usr/local/.
'''
#include </usr/local/include/gdal_priv.h>
#include </usr/local/include/cpl_conv.h>
'''
i used full paths, but I'll try your method next time.  Thanks very much for your help and your work over
at GDAL-dev as well.
