### ISSUE TITLE
error when building

### ISSUE THREAD

**Issue by Remi-C** [Oslandia/horao#27]
Hey,
here is the error I get while building

    73%] Building CXX object src/osgGIS/CMakeFiles/SFosg_test.dir/SFosg.cpp.o
    In file included from .../horao/src/osgGIS/SFosg.cpp:24:0:
    /usr/local/include/liblwgeom.h:1918:56: erreur: new declaration ‘char* strcasestr(const char*, const char*)’
    /usr/include/string.h:369:28: erreur: ambiguates old declaration ‘const char* strcasestr(const char*, const char*)’
    make[2]: *** [src/osgGIS/CMakeFiles/SFosg_test.dir/SFosg.cpp.o] Erreur 1
    make[1]: *** [src/osgGIS/CMakeFiles/SFosg_test.dir/all] Erreur 2
    make: *** [all] Erreur 2

Doesn't look like an Horao error??
Cheers

**Comment by vmora** [comment]
try to add the definition HAVE_STRCASESTR

   ADD_DEFINITIONS("HAVE_STRCASESTR=1")

**Comment by Remi-C** [comment]
Hey, thanks @vmora 
I added `ADD_DEFINITIONS(-DHAVE_STRCASESTR=1)`
to the beginning of the CMakeList.txt

Now another error with gdal .  
`.../horao/src/osgGIS/ReaderWriterMNT.cpp:35:28: erreur fatale: gdal/gdal_priv.h : Aucun fichier ou dossier de ce type`
I checked, and the only `gdal_priv.h` I got is in `/usr/local/include/gdal_priv.h`

**Comment by vmora** [comment]
gdal installs there if it's custom build and under gdal/ for ubuntu systems. Just remove '.gdal/' from the include and it should work fine.

**Comment by Remi-C** [comment]
Thanks,
I removed the `gdal/` from 2 includes lines in `ReaderWriterPOSTGIS.cpp` and `ReaderWriterMNT.cpp`.
Now it compiles !

**Comment by strk** [comment]
Why was this closed ? Shouldn't gdal install layout be detected at configure time ?
I'm having the same problem.

**Comment by strk** [comment]
NOTE: the HAVE_STRCASESTR issue is being tracked in #28, let's keep this for GDAL ?

**Comment by strk** [comment]
Now this one (strcasestr fixed by 1a56f901bce6927d3d5d8685b8a2efd7c86bd027) --
We could always just include gdal_priv.h and rely on CFLAGS  to add ../gdal to the include path maybe ?

**Comment by vmora** [comment]
I closed #28, the fix is marked for #27, but nevermind, for the gdal include, I'll try something.

**Comment by strk** [comment]
PostGIS does indeed just ``#include "gdal.h"`` and relies on ``-I`` switch to find it

**Comment by vmora** [comment]
It actually works, I installed the systems gdal, and cmake (2.8) finds the gdal subdir by itself.
