### ISSUE TITLE
INSTALL mention `horaoViewerd` but it does not exist

### ISSUE THREAD

**Issue by strk** [Oslandia/horao#29]
After build I have an `horaoViewer` under bin, but no `horaoViewerd`. Is it a typo in the INSTALL.md file to mention `horaoViewerd` ?

**Comment by vmora** [comment]
No, that's an error in the plugin (which looks for the debug version here)

**Comment by vmora** [comment]
Actually, I double checked, and the debug version is not referenced in the plugin as the default value (it used to be I think)

So maybe you have a qgis settings still pointing on horaoViewerd

**Comment by strk** [comment]
Maybe I wasn't clear.
I'm saying that there's no ```horaoViewerd``` under the bin/ directory after build, but the INSTALL.md file refers to it. This has nothing to do with runtime (yet).

Either the bug is in the INSTALL.md file (a typo) or in the (my) build failing to build it.

There is an ``horaoViewer`` (without ending 'd') though, in my build.

**Comment by strk** [comment]
So I confirm qgis tries to start `horaoViewer`, not `horaoViewerd`, so it is a typo in INSTALL to request installing `horaoViewerd`. Thanks for the fix.
