### ISSUE TITLE
Error Building against PostGIS 2.2.2, and gdal 2.1.0

### ISSUE THREAD

**Issue by pjduplooy** [Oslandia/horao#42]
Hi guys

I am building horao master against PostGIS 2.2.2, and gdal 2.1.0, on Ubuntu 16.04, with the PostGIS and gdal binaries from the OsgeoLive Nightly ppa (They have compiled their binaries against gdal 2.1.0).

lwgeom is also 2.2.2.

The error I get is:

/home/user/Temp/horao/src/osgGIS/ReaderWriterPOSTGIS.cpp: In member function ‘virtual osgDB::ReaderWriter::ReadResult ReaderWriterPOSTGIS::readNode(const string&, const Options*) const’:
/home/user/Temp/horao/src/osgGIS/ReaderWriterPOSTGIS.cpp:282:94: error: ignoring return value of ‘CPLErr GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, GSpacing, GSpacing, GDALRasterIOExtraArg*)’, declared with attribute warn_unused_result [-Werror=unused-result]
                     band->RasterIO( GF_Read, posX, posY, 1, 1, blockData, 1, 1, dType, 0, 0 );
                                                                                              ^
[ 86%] Building CXX object src/osgGIS/CMakeFiles/osgdb_postgis.dir/SFosg.cpp.o
/home/user/Temp/horao/src/osgGIS/ReaderWriterMNT.cpp: In member function ‘virtual osgDB::ReaderWriter::ReadResult ReaderWriterMNT::readNode(const string&, const Options*) const’:
/home/user/Temp/horao/src/osgGIS/ReaderWriterMNT.cpp:231:90: error: ignoring return value of ‘CPLErr GDALRasterBand::RasterIO(GDALRWFlag, int, int, int, int, void*, int, int, GDALDataType, GSpacing, GSpacing, GDALRasterIOExtraArg*)’, declared with attribute warn_unused_result [-Werror=unused-result]
             band->RasterIO( GF_Read, x, y, w * Lx, h * Ly, blockData, w, h, dType, 0, 0 );
                                                                                          ^
cc1plus: all warnings being treated as errors
src/osgGIS/CMakeFiles/osgdb_postgis.dir/build.make:62: recipe for target 'src/osgGIS/CMakeFiles/osgdb_postgis.dir/ReaderWriterPOSTGIS.cpp.o' failed
make[2]: *** [src/osgGIS/CMakeFiles/osgdb_postgis.dir/ReaderWriterPOSTGIS.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
cc1plus: all warnings being treated as errors
src/osgGIS/CMakeFiles/osgdb_mnt.dir/build.make:62: recipe for target 'src/osgGIS/CMakeFiles/osgdb_mnt.dir/ReaderWriterMNT.cpp.o' failed
make[2]: *** [src/osgGIS/CMakeFiles/osgdb_mnt.dir/ReaderWriterMNT.cpp.o] Error 1
CMakeFiles/Makefile2:338: recipe for target 'src/osgGIS/CMakeFiles/osgdb_mnt.dir/all' failed
make[1]: *** [src/osgGIS/CMakeFiles/osgdb_mnt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 90%] Linking CXX executable ../../bin/SFosg_test
[ 90%] Built target SFosg_test
CMakeFiles/Makefile2:301: recipe for target 'src/osgGIS/CMakeFiles/osgdb_postgis.dir/all' failed
make[1]: *** [src/osgGIS/CMakeFiles/osgdb_postgis.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Any help on this?  Any further info that you might need?

Oh, Cmake is 3.5.1, OSG is 3.2.3, CGAL is 4.7, SFCGAL is 1.2.2.

I have used the instructions on the workshop-3d (github/oslandia) to install the required packages, but have used libgdal-dev (2.1.0), instead of libgdal1-dev if that makes a difference at all.

Any help would be greatly appreciated.

Pieter

**Comment by mhugo** [comment]
Apparently, we a re bit too strict about warnings.
Could you try adding "(void)" in front of these two lines here :
https://github.com/Oslandia/horao/blob/master/src/osgGIS/ReaderWriterMNT.cpp#L231
and there :
https://github.com/Oslandia/horao/blob/master/src/osgGIS/ReaderWriterPOSTGIS.cpp#L282
?

**Comment by pjduplooy** [comment]
Hi mhugo.

I do not really understand what to do here. I have entered the void as you indicated exactly but the build fails with 2 errors. One is about expected ; before band and the other about statement has no effect.

I am not proficient in c to make the changes work. Hope you can show me how. 

Pieter

**Comment by mhugo** [comment]
I've just fixed the problem in the master. Please retry

**Comment by pjduplooy** [comment]
Hi mhugo.

Confirmed working on my box.

Thank you so much for the quick fix!!

Pieter
